### ISSUE TITLE
"webhook returned response.patch but not response.patchType" error

### ISSUE THREAD

**Issue by tmmorin** [rancher/webhook#158]
Internal Reference: SURE-5818

## Context

We're working on a component that creates `Cluster.provisioning.cattle.io` resources from a service tenant (I'm ready to share about what it does, but don't think this is so important to resolve the issue we see).

And we run into a case where the creation of this resource result in the following message being produced by kubernetes apiserver:

```
Internal error occurred: failed calling webhook "rancher.cattle.io": 
received invalid webhook response: webhook returned response.patch but not response.patchType
```

## The manifest that we use

```yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: foo
  namespace: default
  annotations:
    field.cattle.io/description: foo
    field.cattle.io/creatorId: "system:serviceaccount:ourns:our-controller"   
      # not the real value, we set here something that matches the actual
      # service account that creates the object to pass the validating part of the webhook
  labels:     # we have some labels that we set 
    bar: foo
```

## Analysis

The following code in k8s api server is generating the error:

https://github.com/kubernetes/apiserver/blob/781f5eee80a0e5357aad5d88f8650d8a4ee8d071/pkg/admission/plugin/webhook/request/admissionreview.go#L68-L70
```go
			if len(r.Response.Patch) > 0 && r.Response.PatchType == nil {
				return nil, fmt.Errorf("webhook returned response.patch but not response.patchType")
			}
```

Let's look at rancher webhook code that produces the patch...

https://github.com/rancher/webhook/blob/HEAD/pkg/patch/patch.go#L22-L30
```go
	patch := admission.PatchResponseFromRaw(oldJSON, newJSON)

	patchJSON, err := json.Marshal(patch.Patches)
	if err != nil {
		return err
	}

	response.Patch = patchJSON
	response.PatchType = patch.PatchType
```

with `PatchResponseFromRaw` being:
```go
func PatchResponseFromRaw(original, current []byte) Response {
	patches, err := jsonpatch.CreatePatch(original, current)
	if err != nil {
		return Errored(http.StatusInternalServerError, err)
	}
	return Response{
		Patches: patches,
		AdmissionResponse: admissionv1.AdmissionResponse{
			Allowed: true,
			PatchType: func() *admissionv1.PatchType {
				if len(patches) == 0 {
					return nil
				}
				pt := admissionv1.PatchTypeJSONPatch
				return &pt
			}(),
		},
	}
}
```

So `response.PatchType` will be `nil` if `jsonpatch.CreatePatch` returned an empty list (which is the case in our situation, because the only thing that might be added on a `cluster.provisioning.cattle.io` object by the webhook is the `creatorId` annotation, but it won't be added because we already set it ourselves).

But if `jsonpatch.CreatePatch` returned an empty list, then `Patches` above will be an empty list, and in rancher-webhook `patch.go`, `patchJSON` will be the `"[]"` string and  not `nil`, which matches precisely the case where the kube apiserver check would fail.

## Proposed solution

This is sufficient to ensures that `response.Patch` is `nil` if `len(patch.Patches) == 0`, and that the webhook will produce a valid response in all situations:

```diff
--- a/pkg/patch/patch.go
+++ b/pkg/patch/patch.go
@@ -26,7 +26,11 @@ func CreatePatch(old, new interface{}, response *webhook.Response) error {
 		return err
 	}
 
-	response.Patch = patchJSON
+	if len(patch.Patches) == 0 {
+		response.Patch = nil
+	} else {
+		response.Patch = patchJSON
+	}
```

This fix "works for us".

## Summary

In our specific context, we hit this issue which seems simple to fix, even if possibly not typically seen in a  typical Rancher use case.
