### ISSUE TITLE
violates PodSecurity on rancher-webhook

### ISSUE THREAD

**Issue by WMP** [rancher/webhook#239]
Hi, I installed K8S 1.25 using RKE2 without the option enabled  `profile: "cis-1.23"`, then Rancher using helm, and it seems to have pulled rancher-webhook: 

```
helm3 list
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
rancher         cattle-system   1               2023-05-10 15:38:17.898990115 +0200 CEST        deployed        rancher-2.7.3                   v2.7.3     
rancher-webhook cattle-system   1               2023-05-10 13:46:08.906962964 +0000 UTC         deployed        rancher-webhook-2.0.3+up0.3.3   0.3.3 

helm3 get values rancher
USER-SUPPLIED VALUES:
global:
  cattle:
    psp:
      enabled: false
hostname: XXXXXX
ingress:
  ingressClassName: internal
  tls:
    source: secret
privateCA: true


helm3 get values rancher-webhook
USER-SUPPLIED VALUES:
capi:
  enabled: true
global:
  cattle:
    systemDefaultRegistry: ""
mcm:
  enabled: true
priorityClassName: rancher-critical



```

Then I enabled in rke2 options `profile: "cis-1.23"`, and rancher-webhook stopped working: 

```
Warning  FailedCreate  58m    replicaset-controller  Error creating: pods "rancher-webhook-656cd8b9f-h25xh" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "rancher-webhook" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "rancher-webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "rancher-webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "rancher-webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

What am I doing wrong?
